name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main # Скрипт сработает, когда ты сохранишь изменения в ветку main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_ACCESS }}'
          channelId: live
          projectId: erablox # Убедись, что ID проекта в Firebase именно такой
          
